### ISSUE TITLE
Use default arguments naming

### ISSUE THREAD

**Issue by kostiakoval** [radex/SwiftyTimer#12]
When I call a `NSTimer.after` and pass a function, it doesn't have a argument name for second argument. This feels not natural for me regarding that all other functions usually used default or external names.  
```
  NSTimer.after(1.second, close)
```
Using default names don't change the nice trailing closure syntax
```
public class func after(interval: NSTimeInterval, block: () -> Void) -> NSTimer 
...
NSTimer.after(1.second) {
  print("done")
}
```

If you agree I can make a PR :)

**Comment by radex** [comment]
Thanks, but I think that's unnecessary. It reads quite naturally as the passed methods are going to be named with verbs generally. No need for verbosity.

**Comment by kostiakoval** [comment]
Actually it does! your are right! What I was thinking hmmm .... :D
