### ISSUE TITLE
How to stop started timer ?

### ISSUE THREAD

**Issue by cloudjanak** [radex/SwiftyTimer#17]
How to stop started timer ?
can you add name of timer so we can also stop by name

**Comment by radex** [comment]
Call `.invalidate()` on the timer object...

**Comment by cloudjanak** [comment]
NSTimer.every(30.seconds, align) now how i can ?

**Comment by narfdotpl** [comment]
@cloudjanak, you have to have a reference to timer instance, for example:

```swift
let timer = NSTimer.every(30.seconds, align)
// ...
timer.invalidate()
```

**Comment by radex** [comment]
Yep, exactly.
