### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by radex** [radex/SwiftyTimer#20]
PR-s appreciated.

**Comment by radex** [comment]
See: https://github.com/radex/SwiftyUserDefaults/blob/master/Package.swift

**Comment by radex** [comment]
So I tried doing this:

~~~
import PackageDescription

let package = Package(
    exclude: ["Sources/Info.plist", "Sources/SwiftyTimer.h"],
    dependencies: []
)
~~~

But when I try to build that, I get this error:

~~~
test2 » swift build                                                                                                                                                                    ~/Desktop/test2 1 ↵
error: NoSources("/Users/radex/Desktop/test2/Packages/SwiftyTimer-1.3.1-dev/Tests/SwiftyTimerTests.xcodeproj")
~~~

Any ideas? I tried adding `Tests` to excluded folders but it didn't help :(

**Comment by aciidb0mb3r** [comment]
You'll probably need to wait till this is merged https://github.com/apple/swift-package-manager/pull/152 or rename your tests folder and add it in excludes for now

**Comment by radex** [comment]
@aciidb0mb3r Thanks! This works.
