### ISSUE TITLE
Support lower deployment targets than 10.11

### ISSUE THREAD

**Issue by jhoughjr** [radex/SwiftyTimer#24]
I haven't perused the source fully, but I would imagine there is no reason that 10.11 is the deployment target for this. I'm wanting to use it in a project that needs to support mavericks.
My guess is it was an oversight, as it was in my project file.

**Comment by radex** [comment]
Yes, an oversight. I'll accept a patch if you have a few moments to fix this.

**Comment by radex** [comment]
Fixed on master.
