### ISSUE TITLE
How to stop a timer in this timer's closure?

### ISSUE THREAD

**Issue by zxming** [radex/SwiftyTimer#25]
Example:
```
NSTimer.new(every: 1.0) {
    let num = random() % 5
    if num == 3 {
        // I want to stop timer according to this condition
    }
}
```

**Comment by jhoughjr** [comment]
If I recall, that returns the timer instance. so you can do something like:
var foo = NSTimer.new(every: 1.0) {
    let num = random() % 5
    if num == 3 {
        // I want to stop timer according to this condition
           foo.invalidate()
    }
}

**Comment by zxming** [comment]
@jhoughjr  
 May not be used 😐
error: Variable used within its own initial value

**Comment by jhoughjr** [comment]
perhaps you could try something like this:

var timer = NSTimer()

....

timer = NSTimer.new(every: 1.0) {
     let num = random() % 5
    if num == 3 {
        // I want to stop timer according to this condition
         timer.invalidate()
}

That should get around that error since it doesn't refer to itself when the right hand side is evaluated before the left hand side is assigned.

**Comment by zxming** [comment]
thanks, I got it 😊
