### ISSUE TITLE
userinfo ?

### ISSUE THREAD

**Issue by rostik** [radex/SwiftyTimer#26]
Is there a way to add userinfo to nstimer ? so i can access a specific timer when making multiple timers dynamically ?

**Comment by radex** [comment]
Could you please elaborate on your use case?

**Comment by rostik** [comment]
i need to create multiple instances of timer dynamically, to play music at specific times.
but then also be able to to invalidate timers, in case user decides to cancel
i was thinking of passing custom userinfo and then be able to access that particular nstimer based on that

**Comment by radex** [comment]
I still don't understand. Why user info? Why can't you just assign your timers to an array or something?

**Comment by rostik** [comment]
sorry, yes, im sure there are lots of ways of accomplishing what im asking. 
im fairly new to swift, and was able to figure how to do that for user notifications using userinfo, so thought i could re use a similar code.

**Comment by radex** [comment]
Alright. I hope you've figured it out. Sorry, user info doesn't sound at all like a good approach for this.
