### ISSUE TITLE
Swift 2.3 compile error

### ISSUE THREAD

**Issue by shenyufei** [radex/SwiftyTimer#31]
Show in PNG.
Use Xcode 8 and swift 2.3.
I use cocoa pods.
I'm a novice , please tell me detail.
swiftyTimer  Version : 1.4.1
Thank you~ 🤗
![2bd7ee22-9309-4718-b3e1-9b1ce4c7c7b2](https://cloud.githubusercontent.com/assets/13211527/18660079/27d4f89e-7f41-11e6-8e36-3d842844b231.png)

**Comment by radex** [comment]
This isn't version 1.4.1, you have a copy from the `swift3` branch...

**Comment by shenyufei** [comment]
@radex 
![afcff982-38de-4975-87ad-e9c5a45fa346](https://cloud.githubusercontent.com/assets/13211527/18661144/f09fb4bc-7f46-11e6-9935-c1f88f896dd6.png)
You say too simple，please detail,😭

**Comment by radex** [comment]
Weird, have you tried deleting the `Pods/` folder and re-running `pod update`?

**Comment by shenyufei** [comment]
i'll try,wait  a moment
