### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by pjebs** [radex/SwiftyTimer#33]
I was wondering if you can clarify what the difference is between

```
NSTimer.every(0.7.seconds) {
    println(self.status)
}
```

and

```
let timer = NSTimer.new(every: 1.second) {
    println(self.status)
}
```

**Comment by pjebs** [comment]
With the first example do i have to invalidate it somehow?

**Comment by pjebs** [comment]
"If you want to make a timer object without scheduling"...

What do you mean by "without scheduling mean? It seems to start automatically anyway.

**Comment by radex** [comment]
If you do

~~~
let timer = NSTimer.new(every: 1.second) {
    println(self.status)
}
~~~

the timer won't actually start. you'd have to call `timer.start()` on it. `NSTimer.every` is a shorthand.
