### ISSUE TITLE
is it supposed to work on a background queue?

### ISSUE THREAD

**Issue by jaimeagudo** [radex/SwiftyTimer#35]
Thanks for sharing your work. Trying to do something apparently simple but I see nothing on the console and breakpoints don't stop there. What am I getting wrong? 
```
let backgroundQueue = DispatchQueue(label: "1sec",
    qos: .background,
    target: nil)

backgroundQueue.async {
    Timer.every(1.seconds) {
        self.log.debug("Timer tick at \(Date())")
    }
}
```
Cheers

**Comment by radex** [comment]
It won't work, you have to call `.start` on an unscheduled timer with the `.commonModes`, IIRC. Otherwise it will only run on main thread and not when modal. If you're dealing with GCD, you can consider using GCD timers, too.

**Comment by jaimeagudo** [comment]
Thanks for replying, I think it worth to mention on the README. Cheers
